### ISSUE TITLE
Containers not being removed on executing kubeadm reset

### ISSUE THREAD

**Issue by ahab94** [kubernetes-incubator/cri-o#1057] opened 2017-10-24 10:48 UTC
Kubernetes containers are running fine 
```
#runc list
ID                                                                 PID         STATUS      BUNDLE                                                                                                                      CREATED                          OWNER
2daa31a098195cf1fbee5cdc70a265bdbb20ef39e875179232c8f6ed81529394   3881        running     /run/containers/storage/devicemapper-containers/2daa31a098195cf1fbee5cdc70a265bdbb20ef39e875179232c8f6ed81529394/userdata   2017-10-24T10:22:27.577277416Z   root
322734a76219f46039bc57e2d7cb440b01946d8c324085cf29f3b4c0078aca62   3934        running     /run/containers/storage/devicemapper-containers/322734a76219f46039bc57e2d7cb440b01946d8c324085cf29f3b4c0078aca62/userdata   2017-10-24T10:22:29.552255226Z   root
34c08f04d558e9908f8f2b0b17955bc06c8ae95ccc1bb0bbd605a6ebb726470d   4187        running     /run/containers/storage/devicemapper-containers/34c08f04d558e9908f8f2b0b17955bc06c8ae95ccc1bb0bbd605a6ebb726470d/userdata   2017-10-24T10:22:48.096358Z      root
4323965d912866ac88af07a91af436487df219035aeefae55fc9cbc1adb90fb3   4300        running     /run/containers/storage/devicemapper-containers/4323965d912866ac88af07a91af436487df219035aeefae55fc9cbc1adb90fb3/userdata   2017-10-24T10:23:10.416986568Z   root
44a05c82b7136e0a7949abb876e41dd2e6c1e83f4af86b83db2d8d6a730ffd61   4115        running     /run/containers/storage/devicemapper-containers/44a05c82b7136e0a7949abb876e41dd2e6c1e83f4af86b83db2d8d6a730ffd61/userdata   2017-10-24T10:22:42.458071132Z   root
9b40a81a34e39b624791ea768a3116ecbc56dec62d634ae2a50af86eade8cf49   4036        running     /run/containers/storage/devicemapper-containers/9b40a81a34e39b624791ea768a3116ecbc56dec62d634ae2a50af86eade8cf49/userdata   2017-10-24T10:22:34.415192585Z   root
a30164651978734fbf7e45bc43096c79306bafa2e372281ee5251bac54a2d820   3805        running     /run/containers/storage/devicemapper-containers/a30164651978734fbf7e45bc43096c79306bafa2e372281ee5251bac54a2d820/userdata   2017-10-24T10:22:27.424696466Z   root
d73d6ca12c9504aef642810ab3468073dc0724e3b7422d01180b2605330b6c4c   3827        running     /run/containers/storage/devicemapper-containers/d73d6ca12c9504aef642810ab3468073dc0724e3b7422d01180b2605330b6c4c/userdata   2017-10-24T10:22:27.454661158Z   root
db1d0b2b5effa70fb2e9b17ab193e74f412a4d0df0877f797250b2e4cc8a8ec5   3857        running     /run/containers/storage/devicemapper-containers/db1d0b2b5effa70fb2e9b17ab193e74f412a4d0df0877f797250b2e4cc8a8ec5/userdata   2017-10-24T10:22:27.531431777Z   root
f61951bc8bc50a3d19dfbafec9dd98de9e791251446d4b727e63ec1d5180226f   4367        running     /run/containers/storage/devicemapper-containers/f61951bc8bc50a3d19dfbafec9dd98de9e791251446d4b727e63ec1d5180226f/userdata   2017-10-24T10:23:16.420254198Z   root
```
but when i do 
```
kubeadm reset
[preflight] Running pre-flight checks
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Removing kubernetes-managed containers
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/lib/etcd]
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
```
It doesn't delete the containers it is supposed to.
```
runc list
ID                                                                 PID         STATUS      BUNDLE                                                                                                                      CREATED                          OWNER
2daa31a098195cf1fbee5cdc70a265bdbb20ef39e875179232c8f6ed81529394   3881        running     /run/containers/storage/devicemapper-containers/2daa31a098195cf1fbee5cdc70a265bdbb20ef39e875179232c8f6ed81529394/userdata   2017-10-24T10:22:27.577277416Z   root
322734a76219f46039bc57e2d7cb440b01946d8c324085cf29f3b4c0078aca62   0           stopped     /run/containers/storage/devicemapper-containers/322734a76219f46039bc57e2d7cb440b01946d8c324085cf29f3b4c0078aca62/userdata   2017-10-24T10:22:29.552255226Z   root
34c08f04d558e9908f8f2b0b17955bc06c8ae95ccc1bb0bbd605a6ebb726470d   4187        running     /run/containers/storage/devicemapper-containers/34c08f04d558e9908f8f2b0b17955bc06c8ae95ccc1bb0bbd605a6ebb726470d/userdata   2017-10-24T10:22:48.096358Z      root
4323965d912866ac88af07a91af436487df219035aeefae55fc9cbc1adb90fb3   4300        running     /run/containers/storage/devicemapper-containers/4323965d912866ac88af07a91af436487df219035aeefae55fc9cbc1adb90fb3/userdata   2017-10-24T10:23:10.416986568Z   root
44a05c82b7136e0a7949abb876e41dd2e6c1e83f4af86b83db2d8d6a730ffd61   4115        running     /run/containers/storage/devicemapper-containers/44a05c82b7136e0a7949abb876e41dd2e6c1e83f4af86b83db2d8d6a730ffd61/userdata   2017-10-24T10:22:42.458071132Z   root
9b40a81a34e39b624791ea768a3116ecbc56dec62d634ae2a50af86eade8cf49   4036        running     /run/containers/storage/devicemapper-containers/9b40a81a34e39b624791ea768a3116ecbc56dec62d634ae2a50af86eade8cf49/userdata   2017-10-24T10:22:34.415192585Z   root
a30164651978734fbf7e45bc43096c79306bafa2e372281ee5251bac54a2d820   3805        running     /run/containers/storage/devicemapper-containers/a30164651978734fbf7e45bc43096c79306bafa2e372281ee5251bac54a2d820/userdata   2017-10-24T10:22:27.424696466Z   root
d73d6ca12c9504aef642810ab3468073dc0724e3b7422d01180b2605330b6c4c   3827        running     /run/containers/storage/devicemapper-containers/d73d6ca12c9504aef642810ab3468073dc0724e3b7422d01180b2605330b6c4c/userdata   2017-10-24T10:22:27.454661158Z   root
db1d0b2b5effa70fb2e9b17ab193e74f412a4d0df0877f797250b2e4cc8a8ec5   3857        running     /run/containers/storage/devicemapper-containers/db1d0b2b5effa70fb2e9b17ab193e74f412a4d0df0877f797250b2e4cc8a8ec5/userdata   2017-10-24T10:22:27.531431777Z   root
f61951bc8bc50a3d19dfbafec9dd98de9e791251446d4b727e63ec1d5180226f   4367        running     /run/containers/storage/devicemapper-containers/f61951bc8bc50a3d19dfbafec9dd98de9e791251446d4b727e63ec1d5180226f/userdata   2017-10-24T10:23:16.420254198Z   root
```
Which creates problem when i try to do `kubeadm init` again.  Issues like `getSockOpt Connection refused` since ports are already in used.

On slave the containers keep on accumulating on each `kubeadm reset` and `kubeadm init` Using all of the resources system has.

### Quick fix 
run the following command on both master and slaves
1: ```runc list -q | while read -r line; do runc delete -f "$line"; done```
2: ```reboot```
3: ```kubeadm init``` on master ```Kubeadm join``` on slave.
```
crio version 1.0.0-rc3-dev
commit: "e5749088b22f01d0913413f770b309926eda3e28"
```

```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rhatdan** [comment] 2017-10-24 12:06
@runcom @mrunalp If this is true, would seem to be a large bug.

**Comment by runcom** [comment] 2017-10-24 12:10
This doesn't sound that bad, I can see either kubeadm isn't actually calling Stop and Remove in the CRI-O or we have some silly bug in our remove routine. Else, I think kubeadm is just stopping Docker and containers go down but that's not true for cri-o, I'll look into this.

**Comment by runcom** [comment] 2017-10-25 08:09
Right, so, the problem is kubeadm assumes docker unfortunately:
```
108         fmt.Println("[reset] Removing kubernetes-managed containers")
109         if err := exec.Command("sh", "-c", "docker ps -a --filter name=k8s_ -q | xargs -r docker rm --force --volumes").Run(); err != nil {
110             fmt.Println("[reset] Failed to stop the running containers")
111         }
```

**Comment by runcom** [comment] 2017-10-25 08:22
Created an issue in kubeadm https://github.com/kubernetes/kubeadm/issues/508

**Comment by sameo** [comment] 2017-10-25 08:22
@runcom fwiw, I started to look at this.

**Comment by runcom** [comment] 2017-10-25 08:23
awesome, look at https://github.com/kubernetes/kubeadm/issues/508 then, as it explain how it could be done with crictl also

**Comment by runcom** [comment] 2017-10-25 08:23
The problem is kubeadm calls the docker binary directly but when running with cri-o there are no docker containers (rather, we do have runc containers)

**Comment by rhatdan** [comment] 2017-10-25 12:37
Excellent lets get PRs to them to clean this up.

**Comment by runcom** [comment] 2017-11-06 20:32
Fixed in kubeadm master

**Closed by runcom** 2017-11-06 20:32 UTC
