### ISSUE TITLE
How can we get nvidia hook to work with CRI-O.

### ISSUE THREAD

**Issue by rhatdan** [kubernetes-incubator/cri-o#1222] opened 2017-12-14 15:04 UTC
@flx42 We would like to work with you to get your runc hook to work with CRI-O.  

CRI-O reads a configuration file for each hook in 
/usr/share/containers/oci/hooks.d

Here is a couple of examples of hooks.  The first one only runs if the container has bind mounts and only runs during the prestart phase.
```
# cat /usr/share/containers/oci/hooks.d/oci-umount.json 
{
    "hasbindmounts": true,
    "hook": "/usr/libexec/oci/hooks.d/oci-umount",
    "stages": [ "prestart" ]
}
```
oci-register-machine only runs if the cmd matches the regex, and runs in the prestart and poststop section.
```
#: cat /usr/share/containers/oci/hooks.d/oci-register-machine.json 
{
    "cmd": [".*/init$" , ".*/systemd$" ],
    "hook": "/usr/libexec/oci/hooks.d/oci-register-machine",
    "stages": [ "prestart", "poststop" ]
}

We also support regex on Annotations.

**Comment by flx42** [comment] 2017-12-14 18:31
Hello @rhatdan,

First of all, your version of runc needs this commit: https://github.com/opencontainers/runc/commit/d7c264aaf1f655a64baa981d2d0bf7a78e4f50d9
If that's the case, you can simply use the binary `nvidia-container-runtime-hook` as a prestart hook.
This hook is shipped by our `nvidia-container-runtime` package. The instructions to setup the repo are here: https://nvidia.github.io/nvidia-container-runtime/

**Comment by flx42** [comment] 2017-12-14 18:32
By the way, our hook detects if it has anything to do by checking the environment variables of the container.
If the container doesn't have `NVIDIA_VISIBLE_DEVICES` set, our hook will be no-op.

**Comment by runcom** [comment] 2017-12-14 18:38
> First of all, your version of runc needs this commit: opencontainers/runc@d7c264a

yup, the runc we use does have that!

**Comment by flx42** [comment] 2017-12-14 18:40
I think regex on annotations would be even better, but I don't think we have a way to bake that into our base CUDA images on DockerHub. Dockerfiles labels are not transformed to annotations as far as I know.

**Comment by flx42** [comment] 2017-12-14 18:42
Off-topic sorry, but what's your take on this [comment](https://github.com/moby/moby/pull/33375#issuecomment-351730740)? We created our hook to be compatible with runc, docker and CRI-O.

**Comment by rhatdan** [comment] 2017-12-14 18:59
Our goal is to not run the hook at all if at all possible.  Since this hurts our performance.  I guess we could extend the hook checking code to look for environment variables being set,  Then you could add a regex to the config to tell us whether we should run them or not.
The Projectatomic/Docker package that we currently use in OpenShift just launches all hooks stored in a certain directory but we wanted to be smarter about that to improve our performance numbers, especially when the hook is only required for certain container images.

@mrunalp Could you examine the comment linked above.  I think Docker engineers view hooks differently then we do.  I believe there are use cases for both types of hooks.  But I forget the arguments.

**Comment by flx42** [comment] 2017-12-14 19:19
Totally agree with the performance argument. But let's make sure it works as expected first :)
Then, we can either try to add annotations to our images (but will prevent users from bringing custom images), or filter on environment variables.
cc @3XX0

**Comment by rhatdan** [comment] 2017-12-14 19:29
I think if you drop a config with something like

```
cat /usr/share/containers/oci/hooks.d/nvidia.json 
{
    "cmd": [".*"],
    "hook": "/PATHTO/nvidahook",
    "stages": [ "prestart", "poststop" ]
}
```

Then CRI-O will run the hook in the prestart and poststop.  Not sure if you want it in both places.

**Comment by flx42** [comment] 2017-12-14 19:31
We only need `prestart`. Do you need help in testing that? I haven't tried to setup CRI-O yet, so if you do have a machine with GPUs, it might be quicker for you to test it.

**Comment by rhatdan** [comment] 2017-12-14 19:35
No I don't have the hardware to actually test it out.  I just wanted to point out how easy it would be to get it to work with CRI-O.  Please send me an email dwalsh@redhat.com we can talk about this more via email.

**Comment by 3XX0** [comment] 2017-12-14 20:19
My bad, I should have [followed up](https://github.com/kubernetes-incubator/cri-o/pull/562#issuecomment-321895694) earlier.

As @flx42 said, annotation filtering won't be useful with Docker since they decided not to convert `LABEL` to annotations. If you could support environment filtering as well that would be great

**Comment by runcom** [comment] 2017-12-14 20:22
> As @flx42 said, annotation filtering won't be useful with Docker since they decided not to convert LABEL to annotations. If you could support environment filtering as well that would be great

so you want to take LABEL(s) from images and set them as Kube annotation? we can easily do that

**Comment by flx42** [comment] 2017-12-14 20:32
It would work too, but we were actually planning to deprecate our [existing labels](https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.0/base/Dockerfile#L21-22).
What do you think @3XX0?

**Comment by 3XX0** [comment] 2017-12-14 20:52
Wait what are we talking about exactly :)
- OCI annotations
- CRI annotations
- CRI labels
- Docker labels

We could keep one label in our images but it should be something that users can easily add to their custom image or specify on the K8s command line

**Comment by mrunalp** [comment] 2017-12-18 20:34
@flx42 We use hooks a lot and think that they are useful. create/start could be useful in some cases but one needs to evaluate what they are doing as the state of the container when viewed from a OCI hook vs something run in between create/start is different. Hooks could modify more things than what one could after runc create.

**Comment by flx42** [comment] 2018-01-02 22:23
@NiveditaViswanathNVIDIA was able to make it work with `nvidia-container-runtime-hook`, we encountered a few pain points though.

1) It's not possible to pass extra arguments to the hook, only the path to the binary.
I would like to be able to pass extra arguments like `--debug` or `--log=/var/log/myhook.log`.
In our particular case, it needs to be:
`nvidia-container-runtime -prestart`.

2) Currently, the undocumented (?) behavior is that the hook stage (`prestart`, `poststart` or `poststop`) is passed as `argv[1]`. Unless this behavior has been agreed upon, I would prefer that we don't inject arguments on the command-line, and let the users do it. The hook stage could still be passed as an environment variable and/or passed manually for our case (we only need `prestart`).

**Comment by RenaudWasTaken** [comment] 2018-01-13 03:04
Quick update:
I'm getting the annotations from the device plugin to CRIO: https://github.com/kubernetes/kubernetes/pull/58172

**Comment by wking** [comment] 2018-02-22 19:08
> Currently, the undocumented (?) behavior is that the hook stage (`prestart`, `poststart` or `poststop`) is passed as `argv[1]`.

This was also fixed with #1244, which [now uses a `stage` environment variable][1].  The variable is still undocumented (I can file updated docs once #1355 lands), but moving it out of the arguments solves your issue.  Is there anything left to do here?  I think we can close this issue.

> Hooks could modify more things than what one could after runc create.

Just to push back on this issue, I don't think there's anything that you can do in a hook that you couldn't do directly from `crio` taking advantage of the `create` / `start` split.  The benefit of hooks in general is that it's easy for callers to provide their own external executables.  It shouldn't matter if `crio` is running those executables itself at the proper times or delegating their execution to the runtime.  You could also support this sort of pluggable behavior with dynamic linking (or a hook-server API, etc., etc.); that would save the separate-hook-process overhead but be more complicated for callers to setup.

[1]: https://github.com/kubernetes-incubator/cri-o/pull/1244/files#diff-dba9598e19f7903533dc9add98d410d2R432

**Comment by flx42** [comment] 2018-02-22 19:12
> Is there anything left to do here? I think we can close this issue.

@RenaudWasTaken did you test with this patch? Can we close?

**Comment by wking** [comment] 2018-02-22 20:20
> The variable is still undocumented (I can file updated docs once #1355 lands)…

To follow up on this point, I don't think we need the environment variable at all (#1360).  That shouldn't affect the Nvidia hook though, since [you only inject it in pre-start][1].

[1]: https://github.com/kubernetes-incubator/cri-o/issues/1222#issuecomment-351812361

**Comment by rhatdan** [comment] 2018-02-22 21:17
If nvidea is checking for the environment variable then it could cause it to break.

https://github.com/projectatomic/oci-register-machine
https://github.com/projectatomic/oci-systemd-hook
https://github.com/projectatomic/oci-umount
Are the others that would need updating that I know about.

**Comment by RenaudWasTaken** [comment] 2018-02-24 00:19
So the hooks actually work in 1.9
However, with master + PR #1345 the behavior seem to have changed I end up with the following error from the nvidia-hook:
```
starting container process caused "process_linux.go:348: container init caused \"process_linux.go:331: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --utility --compute --pid=31877 /var/lib/containers/storage/devicemapper/mnt/6d36db25c65b1fdde0a482c36b775627501a8968df6d5eb55ba43e8a466d2059/rootfs]\\\\nnvidia-container-cli: detection error: environment variable PATH not found\\\\n\\\"\""
```

@flx42 suggested that I add `export PATH=/usr/sbin:/usr/bin:/sbin:/bin` in the shell wrapper that I use but I'm a bit surprised by this behavior change.
My wrapper being a simple (btw I had to change nvidia-container-runtime to /usr/bin/nvidia-container-runtime-hook since the path wasn't set):
```
#! /bin/sh
/usr/bin/nvidia-container-runtime-hook -prestart
```

@wking @rhatdan do you know what might have changed that behavior?

**Comment by wking** [comment] 2018-02-24 00:27
>     … environment variable PATH not found…

My guess is that runc is just [copying `Env` over to Go's `Cmd`][1] and that [Go uses the host environment if `Env` is `nil`][2].  I think that's a bug on `runc`'s part (although the spec isn't clear enough to say for sure), but the change is due to the `stage` `Env` setting.  #1360 should return you to the old environment inheritance, at least until `runc` is patched to fix it ;).

I agree that you should set `PATH` explicitly if you need it.

[1]: https://github.com/opencontainers/runc/blob/b50fa98d9e5ec3ff58028c46767129607067f961/libcontainer/configs/config.go#L318
[2]: https://golang.org/pkg/os/exec/#Cmd

**Comment by flx42** [comment] 2018-02-24 00:36
Our hook now uses a default value for PATH: https://github.com/NVIDIA/nvidia-container-runtime/commit/95bc87201387845446d6d83b7c7815b348e2a92c

**Comment by wking** [comment] 2018-02-24 01:00
> #1360 should return you to the old environment inheritance, at least until runc is patched to fix it ;).

opencontainers/runc#1738 is the patch removing the environment leakage you used to rely on.

**Comment by rhatdan** [comment] 2018-03-16 18:37
@flx42 This issue is fixed for you now correct?

**Comment by flx42** [comment] 2018-03-16 18:43
I think so, @RenaudWasTaken?

**Comment by RenaudWasTaken** [comment] 2018-03-16 19:00
Last time I tested it that was good.
Is there a code freeze so that we can make sure there wasn't any regression?

I think we should also discuss if and how we can introduce some testing to
prevent future regressions.
-- 
Renaud Gaubert

>

**Comment by rhatdan** [comment] 2018-03-16 20:00
Well we are running CRI-O v1.9.10 in production right now on OpenShift Online.  Our plan is to ship it in OpenShift 3.9 release which is coming in April I believe.  But we are pretty much frozen now, only bugfixes.

**Comment by runcom** [comment] 2018-06-28 11:02
anything left from this issue? @RenaudWasTaken @flx42 @3XX0

**Closed** 2018-06-28 16:28 UTC
