### ISSUE TITLE
issue running tests on rhel

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#140] opened 2016-10-14 08:34 UTC
tests are failing in RHEL pretty often because of `Device or resource busy` errors coming from devmapper and `docker rm`

**Comment by mrunalp** [comment] 2016-10-14 12:05
This could be SELinux.

**Comment by mrunalp** [comment] 2016-10-14 15:24
Can you check the audit log and see if you find anything? Also try running in permissive mode.

**Comment by runcom** [comment] 2016-10-14 15:29
alright, it's selinux, I'm able to run tests (even if some is failing) in RHEL with setenforce 0 /cc @rhatdan

**Comment by runcom** [comment] 2016-10-14 15:31
@mrunalp @rhatdan @rhvgoyal the thing is tests are failing in RHEL pretty often because of `Device or resource busy` errors coming from devmapper and Docker :cry:

**Comment by mrunalp** [comment] 2016-10-14 15:36
@runcom Most likely the resource busy is coming from docker rm. 
@rhvgoyal, what was the final fix that we went with for mount namespaces leaking into machined?

**Comment by rhatdan** [comment] 2016-10-14 16:08
Can I get the AVCs?

**Comment by runcom** [comment] 2016-10-14 16:11
output of `ausearch -m avc` -> https://paste.fedoraproject.org/450214/

**Comment by rhatdan** [comment] 2016-10-14 16:16
Looks like we have to mount the tmp directory with the mountlabel.  But I did not think that ocid would work in enforcing mode yet.  We need to implement all of the storage stuff and finish the wiring.

**Comment by surajssd** [comment] 2016-10-17 06:39
Similar issue on Fedora24 with normal example execution from README

when starting a container:

```bash
$ sudo ocic ctr create --pod d8a4e8b4fa122c578b3383135122184166eaeeee0a34c91eca2da4ebd41b6d5c --config $GOPATH/src/github.com/kubernetes-incubator/cri-o/test/testdata/container_redis.json
a39039cc66435962c2572cdfb5c1b85c0b6e8eb338358130bdb2d31664345755

$ sudo ocic ctr start  --id a39039cc66435962c2572cdfb5c1b85c0b6e8eb338358130bdb2d31664345755                                                                                                       
a39039cc66435962c2572cdfb5c1b85c0b6e8eb338358130bdb2d31664345755
```

logs on process ocid
```bash
[SNIP]
INFO[168386] Signal received: child exited                
/bin/shINFO[168397] Signal received: child exited                
: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory
PID 1146 exited
[SNIP]
```

when checked with the container status
```bash
$ sudo ocic ctr status  --id fbc8117ff0e8854034e2a2a94da8bc4cbe92f05d7b01c552c704ae9a24229b4d                                                                                                      
ID: fbc8117ff0e8854034e2a2a94da8bc4cbe92f05d7b01c552c704ae9a24229b4d
Status: EXITED
Created: 2016-10-17 04:48:27 +0000 UTC
Started: 2016-10-17 04:49:22 +0000 UTC
Finished: 2016-10-17 04:49:22 +0000 UTC
Exit Code: 127
```

AVCs
```bash
ausearch -m avc
----
time->Mon Oct 17 04:09:22 2016
type=AVC msg=audit(1476677362.606:1553): avc:  denied  { read } for  pid=22101 comm="docker-entrypoi" name="ld.so.cache" dev="vda1" ino=1576913 scontext=system_u:system_r:svirt_lxc_net_t:s0:c142,c641 tcontext=unconfined_u:object_r:var_lib_t:s0 tclass=file permissive=0
----
time->Mon Oct 17 04:09:22 2016
type=AVC msg=audit(1476677362.606:1554): avc:  denied  { read } for  pid=22101 comm="docker-entrypoi" name="libc.so.6" dev="vda1" ino=1578093 scontext=system_u:system_r:svirt_lxc_net_t:s0:c142,c641 tcontext=unconfined_u:object_r:var_lib_t:s0 tclass=lnk_file permissive=0
----
time->Mon Oct 17 04:11:44 2016
type=AVC msg=audit(1476677504.140:1603): avc:  denied  { read } for  pid=25157 comm="docker-entrypoi" name="ld.so.cache" dev="vda1" ino=1576915 scontext=system_u:system_r:svirt_lxc_net_t:s0:c142,c641 tcontext=unconfined_u:object_r:var_lib_t:s0 tclass=file permissive=0
----
time->Mon Oct 17 04:11:44 2016
type=AVC msg=audit(1476677504.140:1604): avc:  denied  { read } for  pid=25157 comm="docker-entrypoi" name="libc.so.6" dev="vda1" ino=1578095 scontext=system_u:system_r:svirt_lxc_net_t:s0:c142,c641 tcontext=unconfined_u:object_r:var_lib_t:s0 tclass=lnk_file permissive=0
----
time->Mon Oct 17 04:46:22 2016
type=AVC msg=audit(1476679582.362:1699): avc:  denied  { read } for  pid=30308 comm="docker-entrypoi" name="ld.so.cache" dev="vda1" ino=1576917 scontext=system_u:system_r:svirt_lxc_net_t:s0:c142,c641 tcontext=unconfined_u:object_r:var_lib_t:s0 tclass=file permissive=0
----
time->Mon Oct 17 04:46:22 2016
type=AVC msg=audit(1476679582.362:1700): avc:  denied  { read } for  pid=30308 comm="docker-entrypoi" name="libc.so.6" dev="vda1" ino=1578097 scontext=system_u:system_r:svirt_lxc_net_t:s0:c142,c641 tcontext=unconfined_u:object_r:var_lib_t:s0 tclass=lnk_file permissive=0
----
time->Mon Oct 17 04:49:22 2016
type=AVC msg=audit(1476679762.800:1731): avc:  denied  { read } for  pid=1146 comm="docker-entrypoi" name="ld.so.cache" dev="vda1" ino=1576919 scontext=system_u:system_r:svirt_lxc_net_t:s0:c142,c641 tcontext=unconfined_u:object_r:var_lib_t:s0 tclass=file permissive=0
----
time->Mon Oct 17 04:49:22 2016
type=AVC msg=audit(1476679762.800:1732): avc:  denied  { read } for  pid=1146 comm="docker-entrypoi" name="libc.so.6" dev="vda1" ino=1578099 scontext=system_u:system_r:svirt_lxc_net_t:s0:c142,c641 tcontext=unconfined_u:object_r:var_lib_t:s0 tclass=lnk_file permissive=0
```

various versions:

```bash
$ ocic -v
ocic version 0.0.1

$ runc -v
runc version 1.0.0-rc2
commit: 3abefdff18bc201199c5dfd0e91e941cb4c61376
spec: 1.0.0-rc2-dev

$ sudo docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-53.gite03ddb8.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      e03ddb8/1.10.3
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-53.gite03ddb8.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      e03ddb8/1.10.3
 Built:           
 OS/Arch:         linux/amd64
```

when run `setenforce 0` redis server comes up without problems



So saw that #148 was merged recently so wanted to build ocid again, so stopped `ocid` process without stopping any running containers, restarted ocid with new build, 


```bash
# ocid --runtime $(which runc)
INFO[0000] Starting reaper                              
E1017 05:09:08.608334   26129 ocicni.go:136] error updating cni config: No networks found in /etc/cni/net.d
[SNIP]
INFO[0810] Signal received: child exited                
1:signal-handler (1476681759) Received SIGTERM scheduling shutdown...
INFO[0810] Signal received: child exited                
1:M 17 Oct 05:22:39.251 # User requested shutdown...
1:M 17 Oct 05:22:39.251 * Saving the final RDB snapshot before exiting.
1:M 17 Oct 05:22:39.271 * DB saved on disk
1:M 17 Oct 05:22:39.271 # Redis is now ready to exit, bye bye...
PID 9519 exited
INFO[0810] Signal received: child exited                
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x60ed1e]

goroutine 101 [running]:
panic(0xac3ac0, 0xc82000e130)
        /usr/lib/golang/src/runtime/panic.go:481 +0x3e6
github.com/kubernetes-incubator/cri-o/oci.(*Runtime).UpdateStatus(0xc820337d80, 0x0, 0x0, 0x0)
        /home/vagrant/work/src/github.com/kubernetes-incubator/cri-o/vendor/src/github.com/kubernetes-incubator/cri-o/oci/oci.go:178 +0xf4e
github.com/kubernetes-incubator/cri-o/server.(*Server).PodSandboxStatus(0xc82014de10, 0x7f2d231347d8, 0xc820396cc0, 0xc82049c220, 0x0, 0x0, 0x0)
        /home/vagrant/work/src/github.com/kubernetes-incubator/cri-o/vendor/src/github.com/kubernetes-incubator/cri-o/server/sandbox.go:423 +0x17c
k8s.io/kubernetes/pkg/kubelet/api/v1alpha1/runtime._RuntimeService_PodSandboxStatus_Handler(0xb98060, 0xc82014de10, 0x7f2d231347d8, 0xc820396cc0, 0xc8201407d0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vagrant/work/src/github.com/kubernetes-incubator/cri-o/vendor/src/k8s.io/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2738 +0x168
google.golang.org/grpc.(*Server).processUnaryRPC(0xc8203a6500, 0x7f2d231345d0, 0xc82027a000, 0xc8205ae0f0, 0xc820171bc0, 0x112ea20, 0xc820396c60, 0x0, 0x0)
        /home/vagrant/work/src/github.com/kubernetes-incubator/cri-o/vendor/src/google.golang.org/grpc/server.go:608 +0x10e6
google.golang.org/grpc.(*Server).handleStream(0xc8203a6500, 0x7f2d231345d0, 0xc82027a000, 0xc8205ae0f0, 0xc820396c60)
        /home/vagrant/work/src/github.com/kubernetes-incubator/cri-o/vendor/src/google.golang.org/grpc/server.go:766 +0x10a0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc82021a0b0, 0xc8203a6500, 0x7f2d231345d0, 0xc82027a000, 0xc8205ae0f0)
        /home/vagrant/work/src/github.com/kubernetes-incubator/cri-o/vendor/src/google.golang.org/grpc/server.go:419 +0xa0
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/vagrant/work/src/github.com/kubernetes-incubator/cri-o/vendor/src/google.golang.org/grpc/server.go:420 +0x9a
```

I guess above happened while doing either of these

```bash
$ sudo ocic pod create --config $GOPATH/src/github.com/kubernetes-incubator/cri-o/test/testdata/sandbox_config.json                                                                              
FATA[0000] Creating the pod sandbox failed: rpc error: code = 2 desc = conflict, name default-podsandbox1-0 already reserved 


$ sudo ocic pod list
$ sudo ocic pod status --id d8a4e8b4fa122c578b3383135122184166eaeeee0a34c91eca2da4ebd41b6d5c
2016/10/17 05:25:21 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2016/10/17 05:25:21 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /var/run/ocid.sock: connect: connection refused"; Reconnecting to {"/var/run/oc
id.sock" <nil>}
FATA[0000] getting the pod sandbox status failed: rpc error: code = 13 desc = transport is closing 
```

when restarted `ocid` process after that I am getting errors as mentioned in https://github.com/kubernetes-incubator/cri-o/issues/152


Now to re-create the above env I am not able to get clean environment without having to destroy the VM.

**Comment by rhatdan** [comment] 2016-10-17 12:52
Right this is different in that it is not a test failure.  These are real failures caused by lack of labeling support in the container/storage support.

**Comment by rhatdan** [comment] 2016-10-17 12:53
If you label the image content svirt_sandbox_file_t (container_file_t) SELinux should work for now.

chcon -Rt svirt_sandbox_file_t /var/lib/ocid

**Comment by surajssd** [comment] 2016-10-19 06:07
Thanks @rhatdan that worked :-)

**Closed** 2016-12-17 14:39 UTC
