### ISSUE TITLE
Join pids cgroup with systemd causes "no such device"

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#1196] opened 2017-11-30 22:25 UTC
Probably a race by the time we mkdir the pids cgroups and the time the "cgroup.procs" file appears. Probably on the systemd side. Maybe this is something fixable in runc directly.

The CRI-O failure is here https://ci.openshift.redhat.com/jenkins/job/test_pull_request_crio_e2e_rhel/433/consoleFull#199861745056cbb9a5e4b02b88ae8c2f77

But this has been reported in openshift as well: https://github.com/openshift/origin/issues/16246 and https://github.com/openshift/origin/issues/16994

**Comment by cyphar** [comment] 2017-12-01 05:22
Here's the relevant section of kernel code:

```c
static ssize_t __cgroup1_procs_write(struct kernfs_open_file *of,
				     char *buf, size_t nbytes, loff_t off,
				     bool threadgroup)
{
	struct cgroup *cgrp;
	/* ... */
	cgrp = cgroup_kn_lock_live(of->kn, false);
	if (!cgrp)
		return -ENODEV;
	/* ... */
}
```

As far as I can tell, this is caused by a race between `cgroup_destroy_locked` and `__cgroup1_procs_write`. Effectively there is a window where the cgroup is killed (`cgrp->self.flags &= ~CSS_ONLINE`) but the kernfs reference still exists. Here's the section:

```
static int cgroup_destroy_locked(struct cgroup *cgrp)
	__releases(&cgroup_mutex) __acquires(&cgroup_mutex)
{
	/* ... */

	/*
	 * Mark @cgrp and the associated csets dead.  The former prevents
	 * further task migration and child creation by disabling
	 * cgroup_lock_live_group().  The latter makes the csets ignored by
	 * the migration path.
	 */
	cgrp->self.flags &= ~CSS_ONLINE;

	/* ... */

	/*
	 * Remove @cgrp directory along with the base files.  @cgrp has an
	 * extra ref on its kn.
	 */
	kernfs_remove(cgrp->kn);
	/* ... */
	return 0;
}
```

So maybe what's happening is that `systemd` is trying to delete the directory for some reason?

**Comment by runcom** [comment] 2017-12-01 17:24
another hit just now https://ci.openshift.redhat.com/jenkins/job/test_pull_request_crio_e2e_rhel/454/consoleFull#-91004491656cbb9a5e4b02b88ae8c2f77

**Comment by runcom** [comment] 2017-12-12 12:00
still happening on rhel pretty frequently https://ci.openshift.redhat.com/jenkins/job/test_pull_request_crio_e2e_rhel/485/consoleFull#-88947908258b6e51eb7608a5981914356

**Comment by wking** [comment] 2018-01-19 21:55
#1270 will pull in opencontainers/runc#1683 which will fix this issue.

**Comment by rhatdan** [comment] 2018-03-16 18:29
Since that PR is merged, I am closing this issue.  Reopen if it is not fixed.

**Closed by rhatdan** 2018-03-16 18:29 UTC
Labels: bug
