### ISSUE TITLE
Failed to check if disk space is available for the runtime

### ISSUE THREAD

**Issue by kelseyhightower** [kubernetes-incubator/cri-o#790] opened 2017-08-26 15:11 UTC
Environment:

CRI was build from source.

```
crio --version
```
```
crio version 1.0.0-alpha.0
```

I'm using the latest upstream release of Kubernetes:
```
kubelet --version
```
```
Kubernetes v1.7.4
```

Error logs from the kubelet:

```
E0826 15:03:03.333793    8283 kubelet.go:1729] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": ImagesFsInfo: unknown runtime: remote
I0826 15:03:13.270839    8283 eviction_manager.go:221] eviction manager: synchronize housekeeping
E0826 15:03:13.359981    8283 kubelet.go:1729] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": ImagesFsInfo: unknown runtime: remote
I0826 15:03:23.271194    8283 eviction_manager.go:221] eviction manager: synchronize housekeeping
E0826 15:03:23.386674    8283 kubelet.go:1729] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": ImagesFsInfo: unknown runtime: remote
I0826 15:03:33.271530    8283 eviction_manager.go:221] eviction manager: synchronize housekeeping
E0826 15:03:33.415899    8283 kubelet.go:1729] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": ImagesFsInfo: unknown runtime: remote
I0826 15:03:43.271879    8283 eviction_manager.go:221] eviction manager: synchronize housekeeping
E0826 15:03:43.442615    8283 kubelet.go:1729] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": ImagesFsInfo: unknown runtime: remote
```

**Comment by runcom** [comment] 2017-08-26 17:43
This sounds like a kubelet issue, we always had this log but I'll double check in a moment.

**Comment by runcom** [comment] 2017-08-26 17:44
afaict the docker-cri is also a "remote" runtime and does not implement the imagefsinfo API call in 1.7.x series

**Comment by mrunalp** [comment] 2017-08-26 23:24
@Random-Liu ping. How can we fix this?

**Comment by runcom** [comment] 2017-08-27 08:09
failing is coming from https://github.com/kubernetes/kubernetes/blob/v1.7.4/pkg/kubelet/cadvisor/cadvisor_linux.go#L188-L201 (CRI isn't implemented afaict)

**Comment by mrunalp** [comment] 2017-08-27 14:39
Yeah, I think this could be fixed once CRI requires stats to be returned by implementations. We could wire up a cadvisor fix meanwhile.

**Comment by runcom** [comment] 2017-08-27 14:44
kube won't even call into cadvisor cause it's getting `remote` runtime, we also need a kube fix to the `switch` in https://github.com/kubernetes/kubernetes/blob/v1.7.4/pkg/kubelet/cadvisor/cadvisor_linux.go#L191

**Comment by mrunalp** [comment] 2017-08-27 14:46
Yeah, we would need a switch but the problem is that it won't work for all "remote" runtimes. Hard-coding might be better in the short term in kube.

**Comment by Random-Liu** [comment] 2017-08-29 21:47
@runcom @mrunalp For CRI runtime, we expect to get container metrics through CRI. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto#L76-L80
And image filesystem information, too https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto#L104.

**Comment by mrunalp** [comment] 2017-08-30 03:18
@Random-Liu Thanks! For the short term, we are working on cadvisor integration.

**Comment by runcom** [comment] 2017-09-08 22:10
https://github.com/google/cadvisor/pull/1741

**Closed by runcom** 2017-09-08 22:10 UTC
