### ISSUE TITLE
Fails to pull image if it already exists with different schema version

### ISSUE THREAD

**Issue by jakolehm** [kubernetes-incubator/cri-o#1725] opened 2018-08-07 15:41 UTC
**Description**

While running sonobuoy conformance tests I noticed image pull failures:
```
Failed to pull image "k8s.gcr.io/pause:3.1": rpc error: code = Unknown desc = Error committing the finished image: image with ID "da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e" already exists, but uses a different top layer: that ID is already in use
```

Most likely this happens because my setup has the same pause image with a different name.

**Steps to reproduce the issue:**
1. setup kubernetes with a custom pause image (that is exactly the same as "k8s.gcr.io/pause:3.1")
2. run sonobuoy
3. pods with "k8s.gcr.io/pause:3.1" fail

**Describe the results you received:**

cri-o fails to pull image.

**Describe the results you expected:**

image pull succeeds.

**Output of `crio --version`:**

```
crio version 1.11.1
commit: ""
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Kubernetes 1.11.1 (Kontena Pharos v1.3.0-beta.1 , https://github.com/kontena/pharos-cluster/releases/tag/v1.3.0-beta.1)
- CentOS 7.5
- DigitalOcean

**Comment by runcom** [comment] 2018-08-07 15:43
@nalind could you take a look at this? looks like something that shouldn't happen :confused:

**Comment by rhatdan** [comment] 2018-08-07 20:49
@mtrmac PTAL also

**Comment by mtrmac** [comment] 2018-08-07 21:29
The failure is from `c/image/storage/storageImageDestination.Commit`, because an image with the same image ID (config digest) exists, but the top layer is different on disk and in the pulled image.

That, indeed, should not generally happen (the same config implies the same list of layers). https://github.com/containers/image/pull/472 would be a possible explanation for v2s1 images, but this is v2s2.

It would be interesting to compare the image’s `config.json` and the list of layer IDs, and layer DiffIDs, in CRI-O storage. And, of course, the two differing “top layer” IDs.

> Most likely this happens because my setup has the same pause image with a different name.

AFAICS _naming_ should not matter, and neither should if the image has been re-compressed when copying to a different registry.

(But, of course, _something_ has gone wrong.)

---

My best _guess_: Does the ‘custom pause image (that is exactly the same as "k8s.gcr.io/pause:3.1")’ happen to actually be stored using the “schema 1” format (e.g. in a schema1-only registry)? That does sound fairly unlikely, but it is the only explanation I can think of right now, assuming that the code works as intended. (It’s far more likely that the code is buggy, but then actual debugging instead of guessing would be involved :) )

**Comment by jakolehm** [comment] 2018-08-08 06:42
> My best guess: Does the ‘custom pause image (that is exactly the same as "k8s.gcr.io/pause:3.1")’ happen to actually be stored using the “schema 1” format (e.g. in a schema1-only registry)? That does sound fairly unlikely, but it is the only explanation I can think of right now, assuming that the code works as intended.

Indeed it sounds fairly unlikely but somehow it actually is stored using the "schema 1" format.. not sure how that happened (image is stored in quay.io).

**Comment by jakolehm** [comment] 2018-08-08 07:29
Probably because quay.io does not support image manifest v2 schema 2.

**Comment by mtrmac** [comment] 2018-08-08 21:52
Ah, OK. Would it be easy for you to test CRI-O with a rebased GitHub.com/containers/image, then? Note that you need to _both_ update CRI-O _and_ delete the relevant images from local storage (or, maybe easier, delete all of the storage and start afresh) for the presumed fix to work.

**Comment by mrunalp** [comment] 2018-08-08 22:55
@mtrmac We could create a PR with a rebase of containers/image and see if it helps @jakolehm.

**Comment by mtrmac** [comment] 2018-08-09 17:09
> A PR would make testing easier for sure.

https://github.com/kubernetes-incubator/cri-o/pull/1731

**Comment by rhatdan** [comment] 2018-08-10 13:42
Since the PR was merged, closing the issue.

**Closed by rhatdan** 2018-08-10 13:42 UTC

**Comment by jakolehm** [comment] 2018-11-05 06:40
It seems that this issue still applies if image is first pulled from an older registry (like quay):

```
# crictl pull quay.io/kontena/pause-amd64:3.1
Image is up to date for quay.io/kontena/pause-amd64@sha256:cb4bcb1b386a7b68086564c32f2b13d2429a167d271e7312b1d2ae196b4e0b1a

# crictl pull k8s.gcr.io/pause-amd64:3.1
FATA[0000] pulling image failed: rpc error: code = Unknown desc = Error committing the finished image: image with ID "da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e" already exists, but uses a different top layer: that ID is already in use 
```

Tested with cri-o 1.11.6 on CentOS 7.5.

**Comment by runcom** [comment] 2018-11-05 11:14
@nalind @mtrmac could you take a look at the above please?

**Comment by mtrmac** [comment] 2018-11-05 15:56
This was supposed to be fixed in the linked https://github.com/kubernetes-sigs/cri-o/issues/1725 .

Has anyone checked so far:
- whether that fix is included in the 1.11.6
- whether this is reproducible when starting with _empty_ local containers/storage? (Note that once images are pulled with the old buggy version, the error message will continue to show up; they need to be at least untagged, a fresh storage is easier/more certain to reason about.)

**Comment by jakolehm** [comment] 2018-11-05 15:57
@mtrmac tested with fresh cluster.

**Comment by runcom** [comment] 2018-11-05 16:03
> * whether that fix is included in the 1.11.6

looks like https://github.com/kubernetes-sigs/cri-o/pull/1731/commits/4e7f71b714932dafc6a70e9b6dc09112da478be1 isn't in 1.11 branch and it's been tagged only for 1.12.0 onwards. @jakolehm any chance you'll be able to test with 1.12? We'll try to understand if a backport is feasible meanwhile

**Comment by jakolehm** [comment] 2018-11-05 16:18
@runcom I'll test with 1.12.0 once our CI has cooked a new package.

**Comment by runcom** [comment] 2018-11-05 16:39
> @runcom I'll test with 1.12.0 once our CI has cooked a new package.

could you also test with 1.11.8? that's the latest in 1.11 release and could have that fixed already, not sure if a package is available for centos yet (@lsm5 ptal)

**Comment by mtrmac** [comment] 2018-11-05 16:39
1.11.7 or later should be enough.

**Comment by jakolehm** [comment] 2018-11-05 16:54
1.11.8 works, so most likely also 1.12.0 works.

**Comment by jakolehm** [comment] 2018-11-05 16:56
Confirmed, 1.12.0 works.

**Comment by runcom** [comment] 2018-11-05 17:01
thanks for checking, all good here then!
